# Generated by Django 3.0.6 on 2020-06-08 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200531_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ancket',
            options={'verbose_name': 'form', 'verbose_name_plural': 'forms'},
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='diagnos',
            options={},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={},
        ),
        migrations.AlterModelOptions(
            name='epicriz',
            options={},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'verbose_name': 'patient', 'verbose_name_plural': 'patients'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'question', 'verbose_name_plural': 'qestions'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterField(
            model_name='ancket',
            name='date',
            field=models.CharField(max_length=100, verbose_name='date form'),
        ),
        migrations.AlterField(
            model_name='ancket',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Patient', verbose_name='patient'),
        ),
        migrations.AlterField(
            model_name='disease',
            name='name',
            field=models.CharField(max_length=100, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='epicriz',
            name='lechenie',
            field=models.CharField(default='', max_length=500, null=True, verbose_name='lechenie'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='FIO',
            field=models.CharField(max_length=100, verbose_name='last first middle name'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='address',
            field=models.CharField(max_length=100, verbose_name='adress'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='date_birth',
            field=models.CharField(max_length=100, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='education',
            field=models.CharField(max_length=100, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='job',
            field=models.CharField(max_length=100, verbose_name='place work'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nationality',
            field=models.CharField(max_length=50, verbose_name='nationality'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='number_card',
            field=models.IntegerField(verbose_name='card'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=50, verbose_name='phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='position',
            field=models.CharField(max_length=100, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sex',
            field=models.CharField(max_length=50, verbose_name='sex'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=100, verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Department',
            field=models.CharField(default='', max_length=50, verbose_name='department'),
        ),
        migrations.AlterField(
            model_name='user',
            name='FIO',
            field=models.CharField(default='', max_length=50, verbose_name='last first middle name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Postion',
            field=models.CharField(default='', max_length=50, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='user',
            name='isAdmin',
            field=models.BooleanField(verbose_name='is admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=200, verbose_name='login'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conviction', models.IntegerField(default=0)),
                ('diagnos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Diagnos')),
            ],
        ),
        migrations.CreateModel(
            name='PravilaRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conviction', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Rule')),
            ],
        ),
    ]
