# Generated by Django 3.0.6 on 2020-06-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200608_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pravilarule',
            name='conviction',
        ),
        migrations.RemoveField(
            model_name='rule',
            name='diagnos',
        ),
        migrations.AddField(
            model_name='rule',
            name='disease',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Disease'),
            preserve_default=False,
        ),
    ]
